# Generated by Django 5.2.1 on 2025-05-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'ordering': ['-applied_on']},
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='applied_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('WISH_LIST', 'Wish List'), ('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEWED', 'Interviewed'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='WISH_LIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='myapp.worktype'),
        ),
    ]
