# Generated by Django 5.2.1 on 2025-06-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_worktype_alter_jobmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('WISH_LIST', 'Wish List'), ('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('INTERVIEWED', 'Interviewed'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('REMOVED', 'Removed')], default='WISH_LIST', max_length=20),
        ),
    ]
